ALTER TABLE players
  ADD COLUMN IF NOT EXISTS pos_x DECIMAL(10,4) NULL,
  ADD COLUMN IF NOT EXISTS pos_y DECIMAL(10,4) NULL,
  ADD COLUMN IF NOT EXISTS pos_z DECIMAL(10,4) NULL,
  ADD COLUMN IF NOT EXISTS pos_h DECIMAL(6,2)  NULL,
  ADD COLUMN IF NOT EXISTS appearance_set TINYINT(1) NOT NULL DEFAULT 0;
